language: node_js

os: linux

dist: bionic

node_js:
  - node

cache:
  - yarn

jobs:
  allow_failures:
    - name: 'DMS e2e tests'

  include:
    - name: 'DMS e2e tests'
      if: type = cron
      before_script: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p && yarn build
      script: yarn test:dms:e2e
      after_failure: bash ./scripts/sendscreenshots.sh
    # - name: 'Component docs'
    #   install: yarn
    #   script: yarn build && yarn storybook build-storybook
    #   after_success:
    #     - test $TRAVIS_EVENT_TYPE = pull_request &&
    #       wait-on $SN_BOT_URL -l -t 60000 &&
    #       netlify deploy --site 1747b330-27d8-4ddd-bf74-39469c257010 --auth $NETLIFY_ACCESS_TOKEN --dir ./examples/sn-react-component-docs/storybook-static --message $TRAVIS_PULL_REQUEST
    # - name: 'Sn app'
    #   install: yarn
    #   script: yarn build && yarn snapp build
    #   after_success:
    #     - test $TRAVIS_EVENT_TYPE = pull_request &&
    #       wait-on $SN_BOT_URL -l -t 60000 &&
    #       netlify deploy --site 94fb346c-b540-40f7-aaaf-21eee2a9c891 --auth $NETLIFY_ACCESS_TOKEN --dir ./apps/sensenet/build --message $TRAVIS_PULL_REQUEST
