language: node_js

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

jobs:
  include:
    # - stage: 'Tests'
    #   name: 'Static linting'
    #   script: yarn lint
    # - name: 'Unit Tests'
    #   before_script: yarn build
    #   script: yarn test:coverage
    #   after_success: bash <(curl -s https://codecov.io/bash)
    # - name: 'DMS e2e tests'
    #   dist: trusty
    #   before_script: yarn build
    #   script: yarn test:dms:e2e
    #   # after_failure: bash ./scripts/sendscreenshots.sh
    #   addons:
    #     chrome: stable
    - stage: 'Deploy dms to netlify'
      before_deploy: npm install netlify-cli -g
      script: yarn build && yarn dms build:webpack
      deploy:
        provider: script
        script: netlify deploy -s $DMS_NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./examples/sn-dms-demo/build
        skip_cleanup: true
        on:
          all_branches: true
