language: node_js

dist: trusty

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

jobs:
  include:
    - stage: 'Tests'
      name: 'Static linting'
      script: yarn lint
    - name: 'Unit Tests'
      before_script: yarn build
      script: yarn test:coverage
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: 'DMS e2e tests'
      before_script: yarn build
      script: yarn test:dms:e2e
      # after_failure: bash ./scripts/sendscreenshots.sh
      addons:
        chrome: stable
