name: CI

on: [push]

jobs:
  install:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Yarn install
      uses: Borales/actions-yarn@1.1.0
      with:
        args: install
        
  lint:
    needs: install
    steps:
    - name: ESLint
      uses: Borales/actions-yarn@1.1.0
      with:
        args: lint
        
  build:
     needs: install
     steps:
     - name: ESLint
       uses: Borales/actions-yarn@1.1.0
       with:
         args: lint
