name: CI

on: [push]

jobs:
  install-lint-build-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install, build and test
      uses: Borales/actions-yarn@1.1.0
      with:
        args: |
          install
          build
          lint
          test
